zip -9 ./sakurai.zip\
	./sakurai.exe\
	./game.dll\
	./README.md\
	\
	./assets/palette.raw\
	./assets/bkg1.raw\
	./assets/bkg2.raw\
	./assets/bkg3.raw\
	./assets/bkg4.raw\
	\
	./assets/fx1.jvn\
	./assets/fx2.jvn\
	\
	./assets/player.jvn\
	\
	./assets/enemy-a.jvn\
	./assets/enemy-b.jvn\
	./assets/enemy-c.jvn\
	./assets/enemy-d.jvn\
	./assets/enemy-e.jvn\
	./assets/enemy-f.jvn\
	./assets/enemy-g.jvn\
	\
	./assets/port-a.jvn\
	./assets/port-b.jvn\
	\
	./assets/font1.jvn\
	./assets/font2.jvn
