zip -9 ./tanakas.zip\
	./tanakas.exe\
	./game.dll\
	./README.md\
	\
	./assets/palette.raw\
	./assets/bkg1.raw\
	./assets/bkg2.raw\
	./assets/bkg3.raw\
	./assets/bkg4.raw\
	./assets/title.raw\
	\
	./assets/fx1.jvn\
	./assets/fx2.jvn\
	\
	./assets/sayori.jvn\
	./assets/kuro.jvn\
	\
	./assets/ui-ports.jvn\
	./assets/ui-items.jvn\
	\
	./assets/enemy-a.jvn\
	./assets/enemy-b.jvn\
	./assets/enemy-c.jvn\
	./assets/enemy-d.jvn\
	./assets/enemy-e.jvn\
	./assets/enemy-f.jvn\
	./assets/enemy-g.jvn\
	\
	./assets/font1.jvn\
	./assets/font2.jvn
