zip -9 ./sakurai.zip\
	./sakurai.exe\
	./game.dll\
	./README.md\
	\
	./assets/palette.raw\
	./assets/bkg1.raw\
	./assets/bkg2.raw\
	./assets/bkg3.raw\
	./assets/bkg4.raw\
	./assets/bkg5.raw\
	./assets/bkg6.raw\
	./assets/bkg7.raw\
	./assets/bkg8.raw\
	\
	./assets/fx1.jvn\
	./assets/fx2.jvn\
	\
	./assets/player.jvn\
	./assets/type-a.jvn\
	./assets/type-b.jvn\
	./assets/type-c.jvn\
	./assets/type-d.jvn\
	./assets/type-e.jvn\
	./assets/type-f.jvn\
	./assets/type-g.jvn\
	\
	./assets/port-a.jvn\
	./assets/port-b.jvn\
	\
	./assets/font1.jvn\
	./assets/font2.jvn
